# Generated by Django 5.1.4 on 2024-12-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.CharField(max_length=2047)),
                ("expires_in", models.IntegerField()),
                ("geolocation", models.CharField(max_length=255)),
                ("id_token", models.CharField(max_length=2047)),
                ("refresh_token", models.CharField(max_length=255)),
                ("refresh_expires_in", models.IntegerField()),
                ("scope", models.CharField(max_length=255)),
                ("token_type", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
